### ISSUE TITLE
Drop needs to pull yard data and person data

### ISSUE THREAD

**Issue by dmksystems** [DROCCK/oh-behive#9]
This is needed for visitation data

**Comment by dmksystems** [comment]
Whitelabel Error Page - Not able to pull user data on POST

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Oct 22 19:45:39 PDT 2015
There was an unexpected error (type=Internal Server Error, status=500).
Exception evaluating SpringEL expression: "y.getDropUser().getPerson().getName()" (/dropsite/list:34)

**Comment by celison** [comment]
Person was not being set in the form. Added parameter to get principal user. Added java code to find user ID by username.
